// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package queries

import (
	"database/sql"
)

type Transaction struct {
	ID          int64
	FromAccount sql.NullInt64
	ToAccount   sql.NullInt64
	Amount      sql.NullInt64
	Status      sql.NullInt64
	Flagged     sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
